version: '3'

services:
  web:
    platform: linux/x86_64
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - .:/db.sqlite3
    ports:
      - "8000:8000"