apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-gke-v10
  namespace: production
  labels:
    app: circleci-gke
    version: "10.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circleci-gke
      version: "10.0.0"
  template:
    metadata:
      labels:
        app: circleci-gke
        version: "10.0.0"
    spec:
      containers:
      - name: circleci-gke
        imagePullPolicy: Always
        image: "us.gcr.io/django-demo-cci/circle-gke:latest"
        env:
          - name: SECRET_KEY
            value: dummy
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi