apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-django-demo-v${VERSION}
  namespace: production
  labels:
    app: circleci-gke
    version: "${VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circleci-gke
      version: "${VERSION}"
  template:
    metadata:
      labels:
        app: circleci-gke
        version: "${VERSION}"
    spec:
      containers:
      - name: circleci-gke
        imagePullPolicy: Always
        image: "us.gcr.io/django-demo-cci/circle-gke:${VERSION}"
        env:
          - name: SECRET_KEY
            value: dummy
        ports:
        - containerPort: 8000
#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#            scheme: HTTP
#          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi