version: 2.1

orbs:
  python: circleci/python@1.5.0

workflows:
   main:
    jobs:
      - python/test:
            pkg-manager: pipenv
            test-tool: pytest
            pip-dependency-file: requirements.txt